import sys
sys.path.append("..")

from _231_motifMatrix import profileMotifs, score, countMotifs, consensus
from _251_profileMostProbableKmer import profileMostProbableKmer
from lib import verticalPrint, spacedPrint

def greedyMotifSearch(dna, k, t):
    #computes a collection of strings as best motifs.
    bestMotifs = [row[:k] for row in dna[:t]]
    
    for i in range(len(dna[0]) - k +1):

        motif1 = dna[0][i:i+k]
        candidateMotifs = [motif1]
        for j in range(1,t):
            profile = profileMotifs(candidateMotifs)
            motif_i = profileMostProbableKmer(dna[j],k, profile)
            candidateMotifs.append(motif_i)
        if(score(candidateMotifs) < score(bestMotifs)):
            bestMotifs = candidateMotifs
    return bestMotifs


if __name__ == "__main__": 
    dna = [
        "CAGTAACCGAACACATATGACCGGTCAGATTTCGCAAACATCCCAGGAGATTCGATCTGGCGCCCGATCTTCCAACGTCGTACATCGACATTGGACGTAGTAGGCCATGATACCTGGCAGGTCCGCCCCCGAGAACCATGGAACTACCGACATTGA",
        "GTATATGTCCGGGAACCTTCATATAAGCAATAACAAACCTCATGTGCATGCCCCCGCTTATGAGGCGTTCACGCAGGGCTAGGTTAGGTGGCAAAGGCAACCTAAGTCTTCAGCTGACGGCCCCCACTGGAATTAGGCTATCCTAAGGGTTGGTAG",
        "GTACGTATCGTATATGGCGGGGGGATGATATTCTCTGGAAGCGAATGGTTAAAACCGAATTTGGATATTGCTGCATAAGTCCGGACTGAAAATCGTTATTGGCTACAACTTGAAGTCATGAGGTTAAGGTATAGGACCATGTTCGGTTACATGCTG",
        "CCTGTAACGCGCGCTCCGAGGAACTCTGAATTTAGCGATTATCTTGACGCCCCTTTAGTCGTGTGACTCTTGCGAACTCCCGACGACTATACCTTAAACCGAATATCGGTCGTGCTACCTCCCGGAGACGATATATATGCCCGGCTGGTACCCTGT",
        "GAATGTAATCAAGCACTCAGACCAAACGGTTAGCCACTCTATCATGGGCCGCATTGCTAACAATACGACCGGATTACCTTCTATAGACGAGCTCGCTACTTCTGCGCAGTCTCCCTTTCTTTTTACATACACTAACGTTATGCACTCGCTGCCTAC",
        "AAGCAGTACACCAGCTCGCCGTAGAGAGTCACAATTTGTTCGGCGTCAAGTCCGCATCAGTTTTTTCCCGTCCGCGTTCCCCGCGCATAAGACCGGAGGTGACTCGCAAAGGAAACGTATGAATGGCGGGGCGGGCGAATTTCTTGAATCCGCGTC",
        "AAATTCCCTTACTTATACGCCCGGAACGCATTCTTCTTTTTACGGGTAGGGATGGACTGATGGACAGACAGGCAGTTACCATACTATCAACGGTCAGAATACTCGTCGGAGTGGTACTAAACAATCATGTTGCTATCCGGGCTCTGTTCACGCCAT",
        "AGCGAAAAGCGCTCTGCGATTCAACCCCCAACGGTATCTTGCCGCTTCCGCCAGCGAATGACACGTGCCGCTGTTAGTGATGTACGCGGCCCTCAGAATGACCTGCAAGATTAATGGCCCCTTCACCATATCCGGACGTAAGCTGGATAGGGCCGG",
        "TTGGTACCGACTCAAGATCCTCGGCCGATACACTGACAATACGGCCGGCTTTGCTTAGCATAATAAGTCACCAACTCCCTCCCGGGTATGGCCGTGGTAGTATACTATCACCTCCACTCTCGTTAATACCAAATCCTAATTGAGTTCACCAGGAAT",
        "GCGATATGATTTTGTCTCCTAACATGAGTCTAAAGTGTATGATAATTGATAAATGTCATGAGATATGACCGGACTGAGTAACCGATTACCCAAAATAGACAAGGGTCCACTTTGCTCCCTAGCTAGTGATTAGGATAGCTACTCTACGCGGAGCCG",
        "AATAGTTAGGAATCGCTGGTATAGACGCAGGCAAGAGAAAGTTTCCCTACAAATTTATGTACAATCGTGGAAGCTGGGACAAAGCCTGTGTCGATGTGTTTGGCTGGCACGTTGCGCGGAGTAAGTGAATGATAATAGGACCGGGACAGTTTCCCA",
        "ACGTACCGGCTTGAAAATGGTGTATTGTCGTGCGCCAGCTTGGTAAAGAAGGGAGGCATGCATGATTGAGGCGCTAGAACGTCGGTGCTTGCATTTATAAGGTGAAACCCACCTGAAGACATGACCGGACGTCTGGATTCGTTTGAATAGGTCCGG",
        "GTACTTTCACATTCGCGGACTTGGTACTCGTCACGTAAGCCTCTTAACGCCAAACACGACCGGGGCTTATCAGTTTGTTGGGGTATGGAGCCTGTGCGATATATTTAATCTGACCACGTCACATAAGCCCGGTCCAGGAAGTCGACCGGGGGAAAT",
        "AGCGACAGATGCTGAAACCATTAAGTCGTGTAGGGAGAAAAACCTTATTCATTCCATCGCCATGCCACTCTTTGGCTGCAAACCAAGGCTCGTCCTTAGACGATAGGCTGATAAGACCGGCTTCCGAGAGTGGAGGCTTCATTTCCATAATGCTAG",
        "GTATATGTCCGGTCAATGACACAGTGAACCTACCGAGTCGCAGCGATTGAGATAATTCACCAAGCGCTAGGTTTTATTAGTCGTCTAACACGGAGTGCTATAGGAATAATTAGGTGTGCCCTAATTTACCGGTGCCCGCTCAGCCAAACTCTAATG",
        "GTGTCATCCCTCAGCGGTGTTAGCTAGTTATAGGTCCCTACTGTCCGTCAAGCTAAGGTAATGGAAGTAGTGTTACGAGCAGCCAATATTTGTAATCCCGCAGTTAGAAAATATGGCCGGGTTCCTACTCCCAGATTGTCCTACACGCCCGGCAGA",
        "TCGAAGCTGGGGGTACTCCCCCACATGTCTAGAGTGCAGCTTCGGAAACATCGTACGCTTAGCGGGGATACGAGTGACTCAGTAGGCCCGGTGTTCTACATTTAATGGCCTGGCCTAAGGTAATAAGGCCGGGCGGTATTAACCTTTCAGATGGTT",
        "ACTGAAAACCATCAGATACATTAAGGGCTTAGAGCAGGGGCTTCTATGCTATTACGTTTTGGTTAAAGCCACGCCGTTGCTTACGACCCGCATCCGCAACGAGCCAAAGTCTTTGCTTGGACCTGAGAATTCTAATATAGATGTACATAAGTCCGG",
        "TGATACGACCGGCTAATTTACCATGAGTTTACTATAGCTAAAATTAAAAGCAGTAAACTCTGACATGAGCGCGTTGCTCGTGTCCCCCTAAGTCCCACACCAAGCAGCGGCCAAAAAACCTAGCCTCTACAAGAACCCCCATCTGTTGATGTACTG",
        "CCCTTCGGACGCGTGGTCCGCGTCCTCACAATTGCGGTCCGCCCGACACAAGGTTGAGTCTTGCTCTTTTACTCTGACTGAAGGTGATACGCCCGGTAGAATGACATTCAGCGACAGGAATCTGCAAGAGTAGATTTCTCGCCCGGGCTTAACTAT",
        "TCAAAGCATTCAGCATAGGGCCGGTCGCCAAGTCAGACCTAGAGGAGATGATAGCAATTGTCCAACGAAGATGTATTGTACTTGATGACTAAGCATTCCAGGATGAGATGTCACAATGAAGCGGACCTACTCTAGAATAGCTCGCTATAGGTCCTA",
        "TCGACTCATAAATTCGTGAGAGATCATTCAATATGGGTATACTACTTCGCGCTACCTTTGTTCATTAATACATCCACGCGTAGGCTAGAACTAATCTAAGTATTTGATGAATAGGCCCGGGTAGGAAAAAGCCTGAACCCGAGGGCTACGTCCCGC",
        "TTGTTATGCACGTTCTCTCTTTATGAACGACTCATGAAATAGGACCGGCAGTATTGGACTCGCATTTAGTATAATCAGTCGTGGTATCGATGGTTGTGCCGTCTGGCTCCGGATTTTCGTCACCTGCCCTCCCTAGTCGACTTTAGAAGGAACGGC",
        "GTACCATGTGTGTTGGTCGCCTAACCTGAAAGATAGTAATAGGGCTGTATGCGTCCTCTAGTACATTTCAGAGCGAGATTTAGATTAGAAACCGGCTGCGAATATCCCACAGAGGACCAACCGAGTAAAATGAGTACTACGTTCGGATAAGGCCGG",
        "TGGGTGTGCACATGCGTGTTGCTTTCTGGAAGTCTCTGAACGGAAGTGACATAGAAATCCTGGGGGAACGTTAGGTGCCCAGTTTCTGAATTTTGTATATCAAATTCAGAGACTAGGTGGAGTTCTAAACGACTGTGACTAAGTTTATATGACCGG",

    ]




    verticalPrint(greedyMotifSearch(dna,12,25))

    print(consensus(greedyMotifSearch(dna,12,25)))
