#################################
######## PATTERN COUNT ##########

#Counts how many times a pattern occurs in a string
def patternCount(text, pattern):
    count = 0
    patternLength = len(pattern)
    for i in range (len(text) - patternLength + 1):
        if pattern == text[i:i+patternLength]:
            count+=1
    return count

if __name__ == "__main__": 
    text_pc = "GCCCTGCTCTCTGCTCTCAAGGTTCACCTGCTCTGCTGCTCTCCACTGCTCTTAACCTGCTGCTCTCTTACTGCTCTCTGCTCTGCAAGGACTGCTCTCCTGCTCTTCTGCTCTCCTGCTCTCGATCTGCTCTCGCAGGATACACTGCTCTGGACTGCTCTGCTGCTCTCCTGCTCTCGCTGCTCTTTATCTGCTCTCCTGCTCTCCTGCTCTCTTATCTGCTCTAACTGCTCTGTATCTGCTCTTCCTGCTCTTCTGCTCTCTGCTCTCTGCTCTACTGCTCTAAGAAGCCTGCTCTCTGCTCTCTGCTCTAAGGGTACTGCTCTGCTGCTCTTGCTGCTCTAACCTGCTCTAGGGCTGCTCTCTGCTCTCTGCTCTCGCTGCTCTGACTGCTCTTTCCTGCTCTCTGCTCTGCTCTTGCTGCTCTCTGCTCTCTGCTCTGCTGCTCTACTGCTCTCCTGCTCTCTGCTCTGTTCTAGCTGCTCTACTGCTCTCTGCTCTACGACTCTGCTCTCCTGCTCTCTCTGCTCTACCCTGCTCTCTGCTCTCCGCTGCTCTTTGTGGAAATCTTCCTGCTCTTGCTGCTCTACATGACTACTGCTCTGCCCTGCTCTCCTGCTCTTCTGCTCTCTGCTCTGTGCCTGCTCTCTGCTCTCATACTAGACCATCTGCTCTCACTGCTCTCTTCATCTGTTTCTCCGGCCATCTCTGCTCTCTGCTCTCCTGCTCTCTCGATCTGCTCTTGTACCTGCTCTTCTCTGCTCTCTGCTCTCTGCTCTACCTGCTCTCTGCTCTTTCTGCTCTCTGCTCTAACAAGGTCTGCTCTACTGCTCTGACCTGCTCTTTAGCTGCTCTTCTGCTCTGCTGCTCTAGTTCTGCTCTCTGCTCTCTGCTCTGCTGCTCTCCCTGCTCTCTGCTCTCTGCTCTTAACTGCTCT"
    pattern_pc = "CTGCTCTCT"
    print(patternCount(text_pc, pattern_pc))